// SafePlate — data: recipes, allergen profiles, safe-swap suggestions.
// Allergen "terms" are what the on-device embedding model compares each
// ingredient against — the semantic net that catches hidden allergens
// (pesto -> pine nuts, worcestershire -> anchovies, marzipan -> almonds).

export const ALLERGENS = [
  {
    id: 'peanut', label: 'Peanuts', emoji: '🥜',
    desc: 'peanuts and peanut-derived foods',
    terms: ['peanut', 'peanuts', 'peanut butter', 'groundnut', 'groundnuts', 'satay sauce', 'peanut sauce', 'peanut oil', 'mole sauce', 'mole', 'arachis', 'arachis oil'],
  },
  {
    id: 'tree-nut', label: 'Tree nuts', emoji: '🌰',
    desc: 'tree nuts such as almonds, cashews, walnuts and pine nuts',
    terms: ['almond', 'almonds', 'cashew', 'cashews', 'walnut', 'walnuts', 'pecan', 'pecans', 'pistachio', 'pistachios', 'hazelnut', 'hazelnuts', 'pine nut', 'pine nuts', 'macadamia', 'marzipan', 'almond milk', 'almond flour', 'nutella', 'praline', 'pesto', 'nut butter', 'chestnut'],
  },
  {
    id: 'milk', label: 'Dairy', emoji: '🥛',
    desc: 'milk and dairy products like cheese, butter and cream',
    terms: ['milk', 'butter', 'cheese', 'cream', 'heavy cream', 'yogurt', 'parmesan', 'mozzarella', 'cheddar', 'feta', 'buttermilk', 'ghee', 'whey', 'ricotta', 'mascarpone', 'sour cream', 'condensed milk', 'halloumi', 'casein', 'caseinate', 'lactose', 'lactalbumin', 'paneer'],
  },
  {
    id: 'egg', label: 'Eggs', emoji: '🥚',
    desc: 'eggs and egg-based foods like mayonnaise',
    terms: ['egg', 'eggs', 'mayonnaise', 'mayo', 'aioli', 'meringue', 'egg wash', 'custard', 'hollandaise', 'egg noodles', 'carbonara', 'albumen', 'lysozyme', 'eggnog'],
  },
  {
    id: 'gluten', label: 'Gluten / wheat', emoji: '🌾',
    desc: 'wheat and gluten-containing grains, breads and pastas',
    terms: ['wheat', 'flour', 'all-purpose flour', 'bread', 'breadcrumbs', 'pasta', 'spaghetti', 'linguine', 'noodles', 'pita', 'flour tortilla', 'couscous', 'croutons', 'seitan', 'barley', 'rye', 'semolina', 'pizza dough', 'dumpling wrappers', 'soy sauce', 'burger bun', 'graham', 'graham flour', 'graham crackers', 'spelt', 'farro', 'durum', 'teriyaki', 'teriyaki sauce'],
  },
  {
    id: 'soy', label: 'Soy', emoji: '🫘',
    desc: 'soy products like soy sauce, tofu and miso',
    terms: ['soy', 'soy sauce', 'tofu', 'tempeh', 'miso', 'miso paste', 'edamame', 'tamari', 'soy milk', 'teriyaki', 'teriyaki sauce', 'soy lecithin'],
  },
  {
    id: 'fish', label: 'Fish', emoji: '🐟',
    desc: 'fish and fish-derived sauces like anchovies and fish sauce',
    terms: ['fish', 'salmon', 'tuna', 'cod', 'anchovy', 'anchovies', 'fish sauce', 'worcestershire sauce', 'worcestershire', 'caesar dressing', 'tilapia', 'sea bass'],
  },
  {
    id: 'shellfish', label: 'Shellfish', emoji: '🦐',
    desc: 'shellfish like shrimp, prawns, crab and lobster',
    terms: ['shrimp', 'prawn', 'prawns', 'crab', 'lobster', 'shrimp paste', 'oyster', 'oyster sauce', 'scallop', 'scallops', 'mussels', 'clams', 'squid', 'octopus', 'crayfish', 'calamari', 'langoustine', 'krill', 'cuttlefish', 'scampi'],
  },
  {
    id: 'sesame', label: 'Sesame', emoji: '🌱',
    desc: 'sesame seeds, sesame oil and tahini',
    terms: ['sesame', 'sesame seeds', 'sesame oil', 'tahini', 'hummus', 'halva', 'za\'atar'],
  },
];

// Safe-swap suggestions: matched against the flagged ingredient / term.
export const SWAPS = [
  { match: ['peanut butter', 'peanut sauce', 'satay', 'peanut'], swap: 'sunflower seed butter', note: 'nutty and rich, peanut-free' },
  { match: ['pine nuts', 'pesto'], swap: 'pumpkin-seed pesto', note: 'same green vibe, zero tree nuts' },
  { match: ['marzipan', 'almond'], swap: 'date-cocoa truffle base', note: 'chewy and sweet without almonds' },
  { match: ['cashew', 'walnut', 'pecan', 'pistachio', 'hazelnut', 'nut'], swap: 'toasted sunflower or pumpkin seeds', note: 'the crunch, minus the nuts' },
  { match: ['tahini'], swap: 'sunflower seed butter + lemon juice', note: 'creamy body without sesame' },
  { match: ['sesame oil'], swap: 'olive oil + toasted sunflower seeds', note: 'toasty finish, sesame-free' },
  { match: ['sesame'], swap: 'toasted pumpkin seeds', note: 'same pop, no sesame' },
  { match: ['hummus'], swap: 'tahini-free white bean dip', note: 'same dunkability' },
  { match: ['soy sauce', 'tamari', 'teriyaki'], swap: 'coconut aminos', note: 'soy- and wheat-free umami' },
  { match: ['miso'], swap: 'tahini-free white bean purée + salt', note: 'savory depth without soy' },
  { match: ['tofu', 'tempeh', 'edamame', 'soy'], swap: 'seared chickpea tofu or extra veg', note: 'soy-free protein' },
  { match: ['worcestershire'], swap: 'coconut aminos + a splash of vinegar', note: 'skips the hidden anchovies' },
  { match: ['fish sauce'], swap: 'coconut aminos + pinch of salt', note: 'umami without fish' },
  { match: ['anchov', 'caesar dressing'], swap: 'capers + lemon + olive oil dressing', note: 'briny bite, no fish' },
  { match: ['salmon', 'cod', 'tuna', 'fish'], swap: 'smoky marinated carrot ribbons', note: 'surprisingly “fishy”, no fish' },
  { match: ['shrimp paste'], swap: 'miso paste', note: 'fermented depth, no shellfish (contains soy)' },
  { match: ['shrimp', 'prawn'], swap: 'king oyster mushroom scallops', note: 'same chew, no shellfish' },
  { match: ['crab', 'lobster', 'scallop', 'mussels', 'clams', 'oyster', 'squid', 'octopus'], swap: 'hearts of palm', note: 'briny and tender' },
  { match: ['spaghetti', 'linguine', 'pasta', 'noodles'], swap: 'rice noodles or GF pasta', note: 'gluten-free base' },
  { match: ['flour', 'breadcrumbs'], swap: 'GF flour / GF breadcrumbs', note: '1:1 gluten-free swap' },
  { match: ['pita', 'tortilla', 'bread', 'croutons', 'pizza dough', 'dumpling wrappers', 'bun'], swap: 'corn tortillas / GF wraps / roasted chickpeas', note: 'wheat-free carrier' },
  { match: ['butter'], swap: 'olive oil or vegan butter', note: 'dairy-free richness' },
  { match: ['buttermilk'], swap: 'oat milk + 1 tbsp lemon juice', note: 'same tang, no dairy' },
  { match: ['cream', 'milk'], swap: 'coconut cream / oat milk', note: 'creamy without dairy' },
  { match: ['parmesan', 'mozzarella', 'cheddar', 'feta', 'ricotta', 'cheese', 'halloumi', 'mascarpone'], swap: 'nutritional yeast or vegan cheese', note: 'savory sprinkle, dairy-free' },
  { match: ['yogurt', 'sour cream'], swap: 'coconut yogurt', note: 'cool and tangy' },
  { match: ['mayonnaise', 'mayo', 'aioli'], swap: 'egg-free vegan mayo', note: 'safe for egg allergies' },
  { match: ['egg'], swap: 'flax egg (1 tbsp ground flax + 3 tbsp water)', note: 'binds baked goods egg-free' },
];

export const RECIPES = [
  {
    id: 'satay-skewers', name: 'Chicken Satay Skewers', emoji: '🍢', cuisine: 'Thai', minutes: 35,
    tags: ['grill', 'high-protein'],
    blurb: 'Char-grilled chicken with a rich peanut dipping sauce.',
    ingredients: ['chicken thighs', 'peanut butter', 'soy sauce', 'sesame oil', 'lime juice', 'honey', 'garlic', 'ginger', 'coconut milk'],
    steps: ['Marinate chicken in soy, lime, garlic and ginger for 20 min.', 'Thread onto skewers and grill 4–5 min per side.', 'Whisk peanut butter, coconut milk, sesame oil and honey into a dipping sauce.'],
  },
  {
    id: 'pesto-pasta', name: 'Basil Pesto Pasta', emoji: '🍝', cuisine: 'Italian', minutes: 20,
    tags: ['vegetarian', 'quick'],
    blurb: 'Classic Genovese pesto tossed through spaghetti.',
    ingredients: ['spaghetti', 'fresh basil', 'pine nuts', 'parmesan', 'garlic', 'olive oil', 'lemon juice', 'salt'],
    steps: ['Blitz basil, pine nuts, garlic, parmesan and olive oil into pesto.', 'Boil spaghetti until al dente; save a cup of pasta water.', 'Toss with pesto, loosening with pasta water; finish with lemon.'],
  },
  {
    id: 'buddha-bowl', name: 'Quinoa Buddha Bowl', emoji: '🥗', cuisine: 'Fusion', minutes: 30,
    tags: ['vegan', 'meal-prep'],
    blurb: 'Roast veg, quinoa and a creamy tahini-lemon drizzle.',
    ingredients: ['quinoa', 'chickpeas', 'tahini', 'avocado', 'kale', 'sweet potato', 'lemon juice', 'olive oil', 'cumin'],
    steps: ['Roast sweet potato and chickpeas with cumin at 200°C for 25 min.', 'Cook quinoa; massage kale with olive oil and salt.', 'Whisk tahini with lemon and water; drizzle over everything.'],
  },
  {
    id: 'green-curry', name: 'Thai Green Curry', emoji: '🍛', cuisine: 'Thai', minutes: 30,
    tags: ['one-pot', 'spicy'],
    blurb: 'Coconut-green curry with bamboo shoots and basil.',
    ingredients: ['chicken breast', 'green curry paste (shrimp paste)', 'coconut milk', 'bamboo shoots', 'thai basil', 'fish sauce', 'jasmine rice', 'lime'],
    steps: ['Fry curry paste in coconut cream until fragrant.', 'Add chicken, coconut milk and bamboo shoots; simmer 12 min.', 'Season with fish sauce and lime; serve over jasmine rice.'],
  },
  {
    id: 'bean-tacos', name: 'Black Bean Tacos', emoji: '🌮', cuisine: 'Mexican', minutes: 20,
    tags: ['vegan', 'quick'],
    blurb: 'Smoky beans, crunchy slaw and avocado in corn tortillas.',
    ingredients: ['corn tortillas', 'black beans', 'avocado', 'cabbage', 'salsa', 'lime', 'cilantro', 'smoked paprika'],
    steps: ['Warm beans with smoked paprika and a splash of salsa.', 'Toss cabbage with lime and salt.', 'Fill warm corn tortillas; top with avocado and cilantro.'],
  },
  {
    id: 'veggie-omelette', name: 'Garden Veggie Omelette', emoji: '🍳', cuisine: 'French', minutes: 15,
    tags: ['vegetarian', 'breakfast'],
    blurb: 'Folded eggs with spinach, mushrooms and cheddar.',
    ingredients: ['eggs', 'cheddar', 'spinach', 'mushrooms', 'butter', 'chives', 'salt', 'pepper'],
    steps: ['Sauté mushrooms and spinach in butter.', 'Pour in beaten eggs; swirl until just set.', 'Add cheddar, fold, and shower with chives.'],
  },
  {
    id: 'pancakes', name: 'Buttermilk Pancakes', emoji: '🥞', cuisine: 'American', minutes: 25,
    tags: ['vegetarian', 'breakfast'],
    blurb: 'Tall, fluffy stacks with maple syrup.',
    ingredients: ['all-purpose flour', 'buttermilk', 'eggs', 'butter', 'maple syrup', 'baking powder', 'sugar', 'vanilla'],
    steps: ['Whisk dry ingredients; fold in buttermilk, eggs and melted butter.', 'Rest batter 10 min for extra lift.', 'Griddle until golden both sides; serve with maple syrup.'],
  },
  {
    id: 'teriyaki-salmon', name: 'Teriyaki Salmon', emoji: '🐟', cuisine: 'Japanese', minutes: 25,
    tags: ['high-protein', 'quick'],
    blurb: 'Lacquered salmon over rice with sesame.',
    ingredients: ['salmon fillets', 'soy sauce', 'honey', 'ginger', 'garlic', 'sesame seeds', 'jasmine rice', 'spring onion'],
    steps: ['Simmer soy, honey, ginger and garlic into a glaze.', 'Sear salmon skin-side down; brush with glaze.', 'Serve over rice with sesame seeds and spring onion.'],
  },
  {
    id: 'tomato-soup', name: 'Roast Tomato Basil Soup', emoji: '🍅', cuisine: 'Italian', minutes: 40,
    tags: ['vegetarian', 'cozy'],
    blurb: 'Slow-roasted tomatoes blended silky with basil.',
    ingredients: ['tomatoes', 'fresh basil', 'vegetable broth', 'cream', 'garlic', 'onion', 'olive oil', 'sugar'],
    steps: ['Roast tomatoes, onion and garlic at 190°C for 30 min.', 'Blend with broth and basil until smooth.', 'Swirl in cream; season and serve.'],
  },
  {
    id: 'falafel-wrap', name: 'Crispy Falafel Wrap', emoji: '🧆', cuisine: 'Middle Eastern', minutes: 45,
    tags: ['vegan', 'street-food'],
    blurb: 'Herby chickpea falafel, crunchy salad, tahini sauce.',
    ingredients: ['chickpeas', 'pita bread', 'tahini', 'cucumber', 'tomato', 'parsley', 'cumin', 'coriander', 'garlic', 'lemon juice'],
    steps: ['Blitz soaked chickpeas with herbs, garlic and spices; shape balls.', 'Fry until deeply golden.', 'Stuff into pita with salad and tahini-lemon sauce.'],
  },
  {
    id: 'pad-thai', name: 'Classic Pad Thai', emoji: '🍜', cuisine: 'Thai', minutes: 30,
    tags: ['street-food', 'spicy'],
    blurb: 'Tamarind noodles with shrimp, egg and crushed peanuts.',
    ingredients: ['rice noodles', 'shrimp', 'eggs', 'fish sauce', 'tamarind paste', 'peanuts', 'bean sprouts', 'lime', 'palm sugar', 'chives'],
    steps: ['Soak noodles; stir-fry shrimp and scrambled egg.', 'Add noodles with tamarind-fish sauce-sugar mix; toss.', 'Serve with crushed peanuts, sprouts and lime.'],
  },
  {
    id: 'greek-salad', name: 'Village Greek Salad', emoji: '🥙', cuisine: 'Greek', minutes: 15,
    tags: ['vegetarian', 'no-cook'],
    blurb: 'Chunky tomatoes, cucumber, olives and a slab of feta.',
    ingredients: ['feta cheese', 'kalamata olives', 'cucumber', 'tomatoes', 'red onion', 'olive oil', 'oregano', 'red wine vinegar'],
    steps: ['Chop vegetables into large chunks.', 'Dress with olive oil, vinegar and oregano.', 'Crown with a slab of feta and more oregano.'],
  },
  {
    id: 'margherita-pizza', name: 'Margherita Pizza', emoji: '🍕', cuisine: 'Italian', minutes: 60,
    tags: ['vegetarian', 'weekend'],
    blurb: 'Blistered crust, san marzano sauce, fresh mozzarella.',
    ingredients: ['pizza dough (wheat flour)', 'mozzarella', 'tomato sauce', 'fresh basil', 'olive oil', 'semolina flour', 'salt'],
    steps: ['Stretch dough on semolina; top with sauce.', 'Bake at max oven heat until blistered.', 'Add mozzarella and basil for the final 2 min.'],
  },
  {
    id: 'mushroom-risotto', name: 'Mushroom Risotto', emoji: '🍄', cuisine: 'Italian', minutes: 45,
    tags: ['vegetarian', 'cozy'],
    blurb: 'Stirred to creaminess with parmesan and butter.',
    ingredients: ['arborio rice', 'mixed mushrooms', 'parmesan', 'butter', 'white wine', 'onion', 'vegetable broth', 'thyme'],
    steps: ['Sear mushrooms hard; set aside.', 'Toast rice, deglaze with wine, add broth ladle by ladle.', 'Beat in butter and parmesan; fold mushrooms back.'],
  },
  {
    id: 'lentil-dal', name: 'Coconut Lentil Dal', emoji: '🥣', cuisine: 'Indian', minutes: 35,
    tags: ['vegan', 'one-pot'],
    blurb: 'Red lentils simmered in coconut and turmeric.',
    ingredients: ['red lentils', 'coconut milk', 'turmeric', 'cumin seeds', 'garlic', 'ginger', 'tomatoes', 'basmati rice', 'cilantro'],
    steps: ['Bloom cumin, garlic and ginger; add turmeric.', 'Simmer lentils with tomatoes and coconut milk 20 min.', 'Serve over basmati with cilantro.'],
  },
  {
    id: 'shrimp-scampi', name: 'Shrimp Scampi', emoji: '🍤', cuisine: 'Italian-American', minutes: 20,
    tags: ['quick', 'date-night'],
    blurb: 'Garlicky butter shrimp over linguine.',
    ingredients: ['shrimp', 'linguine', 'garlic', 'butter', 'white wine', 'lemon', 'parsley', 'chili flakes'],
    steps: ['Sizzle garlic in butter and olive oil.', 'Add shrimp and wine; cook 2 min.', 'Toss with linguine, lemon and parsley.'],
  },
  {
    id: 'steak-chimichurri', name: 'Steak & Chimichurri', emoji: '🥩', cuisine: 'Argentinian', minutes: 30,
    tags: ['high-protein', 'grill'],
    blurb: 'Seared steak under a bright herby sauce.',
    ingredients: ['sirloin steak', 'parsley', 'garlic', 'olive oil', 'red wine vinegar', 'oregano', 'chili flakes', 'salt'],
    steps: ['Blitz parsley, garlic, vinegar, oil and oregano.', 'Sear steak 3–4 min per side; rest 5 min.', 'Slice against the grain; spoon over chimichurri.'],
  },
  {
    id: 'marzipan-truffles', name: 'Chocolate Marzipan Truffles', emoji: '🍫', cuisine: 'German', minutes: 30,
    tags: ['dessert', 'no-bake'],
    blurb: 'Almond marzipan centers in dark chocolate.',
    ingredients: ['marzipan (almonds)', 'dark chocolate', 'cocoa powder', 'coconut oil', 'sea salt'],
    steps: ['Roll marzipan into balls; chill 15 min.', 'Melt chocolate with coconut oil.', 'Dip, dust with cocoa and sea salt.'],
  },
  {
    id: 'mac-cheese', name: 'Baked Mac & Cheese', emoji: '🧀', cuisine: 'American', minutes: 40,
    tags: ['vegetarian', 'cozy'],
    blurb: 'Three-cheese sauce under a crunchy crumb.',
    ingredients: ['elbow macaroni pasta', 'cheddar', 'mozzarella', 'milk', 'butter', 'all-purpose flour', 'breadcrumbs', 'mustard powder'],
    steps: ['Make a roux; whisk in milk and cheeses.', 'Fold in pasta; top with buttered breadcrumbs.', 'Bake at 190°C until bubbling and golden.'],
  },
  {
    id: 'veggie-dumplings', name: 'Pan-Fried Veggie Dumplings', emoji: '🥟', cuisine: 'Chinese', minutes: 50,
    tags: ['vegan', 'weekend'],
    blurb: 'Cabbage-mushroom filling with a sesame-soy dip.',
    ingredients: ['dumpling wrappers (wheat)', 'cabbage', 'shiitake mushrooms', 'carrot', 'soy sauce', 'sesame oil', 'ginger', 'spring onion'],
    steps: ['Salt cabbage 10 min; squeeze dry; mix filling.', 'Fill and pleat wrappers.', 'Fry, splash with water, steam 3 min; dip in soy-sesame sauce.'],
  },
  {
    id: 'roast-chicken', name: 'Sunday Roast Chicken', emoji: '🍗', cuisine: 'British', minutes: 90,
    tags: ['family', 'weekend'],
    blurb: 'Lemon-rosemary bird with crispy potatoes.',
    ingredients: ['whole chicken', 'potatoes', 'carrots', 'rosemary', 'garlic', 'lemon', 'olive oil', 'salt'],
    steps: ['Rub chicken with oil, salt, lemon and rosemary.', 'Roast at 200°C over chunked vegetables, ~75 min.', 'Rest 15 min; serve with the pan vegetables.'],
  },
  {
    id: 'mango-sticky-rice', name: 'Mango Sticky Rice', emoji: '🥭', cuisine: 'Thai', minutes: 40,
    tags: ['dessert', 'vegan'],
    blurb: 'Coconut sticky rice with ripe mango and sesame.',
    ingredients: ['glutinous rice', 'ripe mango', 'coconut milk', 'sugar', 'sesame seeds', 'salt'],
    steps: ['Steam soaked glutinous rice 20 min.', 'Warm coconut milk with sugar and salt; fold through rice.', 'Plate with mango and toasted sesame seeds.'],
  },
  {
    id: 'bolognese', name: 'Slow Spaghetti Bolognese', emoji: '🍝', cuisine: 'Italian', minutes: 120,
    tags: ['family', 'weekend'],
    blurb: 'A rich ragù with a secret splash of Worcestershire.',
    ingredients: ['spaghetti', 'ground beef', 'crushed tomatoes', 'worcestershire sauce', 'onion', 'carrot', 'celery', 'garlic', 'olive oil', 'parmesan', 'milk'],
    steps: ['Soffritto onion, carrot, celery; brown the beef.', 'Add tomatoes, milk and Worcestershire; simmer low 90 min.', 'Toss with spaghetti; finish with parmesan.'],
  },
  {
    id: 'caesar-salad', name: 'Classic Caesar Salad', emoji: '🥬', cuisine: 'American', minutes: 20,
    tags: ['quick', 'classic'],
    blurb: 'Crunchy romaine, garlicky dressing, golden croutons.',
    ingredients: ['romaine lettuce', 'caesar dressing (anchovies, egg, parmesan)', 'croutons', 'parmesan', 'lemon juice', 'black pepper'],
    steps: ['Whisk dressing with lemon until glossy.', 'Toss romaine with dressing.', 'Shower with croutons, parmesan and pepper.'],
  },
];
